version: '3.8'

services:
  web:
    build:
      context: ./src/web
      args:
        - VERSION=${VERSION:-0.0.1}
    ports:
      - "80:80"
    volumes:
      - ./src/web:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    depends_on:
      - api

  api:
    build:
      context: ./src/api
      args:
        - VERSION=${VERSION:-0.0.1}
    ports:
      - "8000:8000"
    volumes:
      - ./src/api:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_db
      - REDIS_URL=redis://:redis_password@redis:6379/0
    depends_on:
      - db
      - redis

  db:
    build:
      context: ./src/db
      args:
        - VERSION=${VERSION:-0.0.1}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db

  redis:
    build:
      context: ./src/redis
      args:
        - VERSION=${VERSION:-0.0.1}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  test-redis:
    build:
      context: ./src/redis
      dockerfile: Dockerfile.test
    ports:
      - "6380:6379"

volumes:
  postgres_data:
  redis_data:
